### ISSUE TITLE
Update 'Advanced Search' page to the same style as profile pages

### ISSUE THREAD

**Issue by simonhdg** [galoishelley/focusdata_code#117]
Update 'Advanced Search' page to the same style as profile pages
put 1 search condition each line

Style like below
![image](https://cloud.githubusercontent.com/assets/22547097/24908156/5a3f49e0-1f02-11e7-811b-cd097ff30203.png)

**Comment by orochigalois** [comment]
Because of the incompatibility between autoComplete and slickModal, this issue has to be discarded.
