### ISSUE TITLE
Home Page updates

### ISSUE THREAD

**Issue by simonhdg** [galoishelley/focusdata_code#121]
1, update background picture
![bg_3_1](https://cloud.githubusercontent.com/assets/22547097/25033593/bef8ccb8-2122-11e7-8b83-5320bacce977.jpg)

2, Image "Doctor Appointment Centre" size set to same as search result page, font changes to 'Source Sans Pro'
3, Update header padding to "50px 0 10px 0"
![image](https://cloud.githubusercontent.com/assets/22547097/25033465/441d1f86-2121-11e7-9ea7-2732a5e4e73c.png)
4, Update search box padding
![image](https://cloud.githubusercontent.com/assets/22547097/25033580/9c87a9c4-2122-11e7-8436-ae643deace89.png)
5, Update header background color to #F8F9FA
![image](https://cloud.githubusercontent.com/assets/22547097/25039038/0833af02-2145-11e7-8dfd-96c72777162a.png)
6, Update the round button's color to #fae596
![image](https://cloud.githubusercontent.com/assets/22547097/25039084/467e4eac-2145-11e7-8c6a-fcac78f37701.png)
7, Update header dropdown list background color to white (no background color)
![image](https://cloud.githubusercontent.com/assets/22547097/25039119/70f12e7a-2145-11e7-938b-b9761e1b723c.png)
8, "Search" button color changes to '#4f798c'

**Comment by orochigalois** [comment]
7, Update header dropdown list background color to white (no background color)
This will cause the issue below
![image](https://cloud.githubusercontent.com/assets/4133977/25060171/cb24c594-21c9-11e7-9138-33b93cc89729.png)
