### ISSUE TITLE
Search result page - adjust date tabs

### ISSUE THREAD

**Issue by simonhdg** [galoishelley/focusdata_code#124]
1, add 30px gap
2, add a line behind date tabs, color '#4f798c'
3, adjust bg and font color of 'Search'
![image](https://cloud.githubusercontent.com/assets/22547097/25069561/1e929db0-22c8-11e7-88b6-6a0afd5b2593.png)

**Comment by orochigalois** [comment]
2, add a line behind date tabs, color '#4f798c'

This is rejected, because it is not in compliance with the tab color
