### ISSUE TITLE
Doctor Type issue on 'Doctor information update' page

### ISSUE THREAD

**Issue by simonhdg** [galoishelley/focusdata_code#139]
When login as clinic user, on 'Doctor information update' page, the Doctor Type filter currently only display GP and Dentist.
Should be fixed to display all doctor types

![image](https://cloud.githubusercontent.com/assets/22547097/25158524/87918aee-24ec-11e7-85c6-e4917ed345dc.png)

**Comment by orochigalois** [comment]
This is not an issue. The doctor type dropdownlist is binding dynamically.  Currently in DB there are only doctors who are Dentist and GP, that's why only 2 items are showed here
