### ISSUE TITLE
Error message on home page when select Chinese

### ISSUE THREAD

**Issue by simonhdg** [galoishelley/focusdata_code#156]
Error message on home page when select "中文"
Chrome on Win10
Warning: Cannot modify header information - headers already sent by (output started at /home/focus167/drpages.com.au/drpages/index.php:2) in /home/focus167/drpages.com.au/drpages/classes/Language/language.common.php on line 11
![image](https://cloud.githubusercontent.com/assets/22547097/25561940/fa2e810c-2dba-11e7-9b93-fc88ae79e416.png)

**Comment by orochigalois** [comment]
Contact hostpapa, just turn
output_buffering = On 
in php.ini
